rm(list=ls())
library(dplyr)
library(ggplot2)
library(tidyr)
proj_dir = getwd()

# MISSING the raw data generation


###
# Appendix II: Identification of
###
file_path = paste0(proj_dir,'/_data/02/production_data.RData')
load(file_path)

# rank the first question by time
extract_exp_data <-function(data){
  obs_rank = data %>% filter(eid=='Q_10201056649366')  %>% arrange(gid,cmt_time) %>%
    group_by(gid) %>% mutate(rank=row_number()) %>%
    ungroup() %>% select(uid, rank)
  # extract the data
  orig_data = data %>% filter(eid=='Q_10201056649366')%>% filter(y<1) %>% select(uid,gid)
  first_data = data %>% filter(eid=='Q_10201056666357') %>%
    select(uid,gid,y,giveup,is_retain) %>% mutate(y=as.integer(y==1)) %>%
    filter(uid %in% orig_data$uid) %>%
    filter(is_retain==1)
  second_data = data %>% filter(eid=='Q_10200351208705') %>%
    select(uid,gid,y,giveup,is_retain) %>% mutate(y=as.integer(y==1))%>%
    filter(uid %in% orig_data$uid) %>%
    filter(is_retain==1)
  # 0 means
  first_diff = merge(first_data, obs_rank) %>% select(gid,y,rank)%>% arrange(gid,rank) %>% group_by(gid) %>% mutate(rank=row_number())
  first_diff$type = 1
  second_diff = merge(second_data, obs_rank)%>% select(gid,y,rank) %>% arrange(gid,rank) %>% group_by(gid) %>% mutate(rank=row_number())
  second_diff$type = 2

  return(rbind(first_diff, second_diff))
}

# write out the csv
res_wk = extract_exp_data(workdata %>% filter(is_placebo==0) )
output_file_path_1st = paste0(proj_dir, '/_data/03/first_assessment_data_wk.csv')
output_file_path_2nd = paste0(proj_dir, '/_data/03/second_assessment_data_wk.csv')
write.csv(res_wk %>% filter(type==1) %>% select(-type), file=output_file_path_1st, quote=F,row.names=F)
write.csv(res_wk %>% filter(type==2) %>% select(-type), file=output_file_path_2nd, quote=F,row.names=F)

res_wk_retain = extract_exp_data(workdata %>% filter(is_placebo==0) %>% filter(is_retain==1))
output_file_path_1st = paste0(proj_dir, '/_data/03/first_assessment_data_wk_retain.csv')
output_file_path_2nd = paste0(proj_dir, '/_data/03/second_assessment_data_wk_retain.csv')
write.csv(res_wk_retain %>% filter(type==1) %>% select(-type), file=output_file_path_1st, quote=F,row.names=F)
write.csv(res_wk_retain %>% filter(type==2) %>% select(-type), file=output_file_path_2nd, quote=F,row.names=F)

res_bkp_retain = extract_exp_data(bkp_data %>% filter(is_placebo==0) %>% filter(is_retain==1))
output_file_path_1st = paste0(proj_dir, '/_data/03/first_assessment_data_bkp_retain.csv')
output_file_path_2nd = paste0(proj_dir, '/_data/03/second_assessment_data_bkp_retain.csv')
write.csv(res_bkp_retain %>% filter(type==1) %>% select(-type), file=output_file_path_1st, quote=F,row.names=F)
write.csv(res_bkp_retain %>% filter(type==2) %>% select(-type), file=output_file_path_2nd, quote=F,row.names=F)

##################################################
# The sim_exp_data are generated by python code  #
##################################################


# sort the sim result
extract_saving_res <- function(mark){
  sim_exp = read.csv(paste0(proj_dir,'/_data/03/sim_exp_data_',mark,'.txt'),header=F, col.names=c('q','g','is_finish','best_arm','runs','pval','ret'))
  if (mark=='wk'){
    res = res_wk
  }else if(mark=='wk_retain'){
    res = res_wk_retain
  }else if(mark=='bkp_retain'){
    res = res_bkp_retain
  }
  first_diff = res %>% filter(type==1)
  second_diff = res %>% filter(type==2)
  # power
  power_res = sim_exp %>% group_by(q,g) %>% summarize(bpower=mean(as.integer(is_finish==1)), bpower1=mean(as.integer(is_finish==1&best_arm==1)),tpower=mean(pval<0.05))
  power_res$type='power'
  # ret saving
  ret_res = sim_exp %>% group_by(q,g) %>% summarize(simexp = mean(ret))
  ret_res$origin = c(sum(first_diff$y[first_diff$gid != 4])/length(first_diff$y[first_diff$gid != 4]),
                     sum(first_diff$y[first_diff$gid != 2])/length(first_diff$y[first_diff$gid != 2]),
                     sum(second_diff$y[second_diff$gid != 4])/length(second_diff$y[second_diff$gid != 4]),
                     sum(second_diff$y[second_diff$gid != 2])/length(second_diff$y[second_diff$gid != 2]))
  ret_res$type = 'ret'
  # runs saving
  runs_res = sim_exp %>% group_by(q,g) %>% summarize(simexp = mean(runs))
  runs_res$origin = c(length(first_diff$y[first_diff$gid != 4]),
                      length(first_diff$y[first_diff$gid != 2]),
                      length(second_diff$y[second_diff$gid != 4]),
                      length(second_diff$y[second_diff$gid != 2]))
  runs_res$type = 'runs'

  sim_exp_res = rbind(power_res, ret_res, runs_res)
  return(sim_exp_res)
}

stat_wk = extract_saving_res('wk')
stat_wk_retain = extract_saving_res('wk_retain')
stat_bkp_retain = extract_saving_res('bkp_retain')


rm(list=setdiff(ls(),c('proj_dir','workdata','bkp_data','stat_wk','stat_wk_retain','stat_bkp_retain')))
output_file_path = paste0(proj_dir,'/_data/03/production_data.RData')

save.image(output_file_path)
